# Nama organisasi di SonarCloud
sonar.organization=fandhz

# Kunci proyek yang ada di SonarCloud
sonar.projectKey=fandhz_OPSv2

# Nama proyekmu di SonarCloud
sonar.projectName=fandhz

# URL SonarCloud
sonar.host.url=https://sonarcloud.io

# Token autentikasi untuk SonarCloud
sonar.token=51d2a25dff9980e93dbc695abbcb0b05ee12c2a9

sonar.java.binaries=target/classes

